drop table IF EXISTS films CASCADE;
drop table IF EXISTS film_genres CASCADE;
drop table IF EXISTS users CASCADE;
drop table IF EXISTS friends CASCADE;
drop table IF EXISTS film_likes CASCADE;
drop table IF EXISTS reviews CASCADE;
drop table IF EXISTS review_likes CASCADE;
drop table IF EXISTS events CASCADE;
drop table IF EXISTS film_directors CASCADE;
drop table IF EXISTS directors CASCADE;


create TABLE IF NOT EXISTS mpa_ratings
(
    mpa_rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(15)
);
create TABLE IF NOT EXISTS directors
(
    director_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(40)
);

create TABLE IF NOT EXISTS films
(
    film_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(50),
    description         VARCHAR(200),
    release_date        DATE,
    duration_in_minutes INTEGER,
    mpa_rating_id       INTEGER REFERENCES mpa_ratings (mpa_rating_id)
);

create TABLE IF NOT EXISTS film_directors
(
    film_id     INTEGER REFERENCES films (film_id) ON delete CASCADE,
    director_id INTEGER REFERENCES directors (director_id) ON delete CASCADE
);

create TABLE IF NOT EXISTS genres
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR
);

create TABLE IF NOT EXISTS film_genres
(
    film_id  INTEGER REFERENCES films (film_id) ON delete CASCADE,
    genre_id INTEGER REFERENCES genres (genre_id) ON delete CASCADE
);

create TABLE IF NOT EXISTS users
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR,
    login    VARCHAR(20),
    name     VARCHAR(50),
    birthday DATE
);

create TABLE IF NOT EXISTS friends
(
    user_id       INTEGER REFERENCES users (user_id) ON delete CASCADE,
    friend_id     INTEGER REFERENCES users (user_id) ON delete CASCADE,
    status_user   BOOLEAN,
    status_friend BOOLEAN,
    PRIMARY KEY (user_id, friend_id)
);

create TABLE IF NOT EXISTS film_likes
(
    film_id INTEGER REFERENCES films (film_id) ON delete CASCADE,
    user_id INTEGER REFERENCES users (user_id) ON delete CASCADE
);
create TABLE IF NOT EXISTS reviews
(
    review_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR(300),
    is_positive BOOLEAN,
    user_id     INTEGER REFERENCES users (user_id) ON delete CASCADE,
    film_id     INTEGER REFERENCES films (film_id) ON delete CASCADE

);

create TABLE IF NOT EXISTS review_likes
(
    user_id   INTEGER REFERENCES users (user_id) ON delete CASCADE,
    review_id INTEGER REFERENCES reviews (review_id) ON delete CASCADE,
    is_like   BOOLEAN
);

create TABLE IF NOT EXISTS operations
(
    operation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR
);

create TABLE IF NOT EXISTS reviews
(
    review_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR,
    is_positive BOOLEAN,
    user_id     INTEGER REFERENCES users (user_id),
    film_id     INTEGER REFERENCES films (film_id)

);

create TABLE IF NOT EXISTS review_likes
(
    user_id   INTEGER REFERENCES users (user_id),
    review_id INTEGER REFERENCES reviews (review_id),
    is_like   BOOLEAN
);

create TABLE IF NOT EXISTS events
(
    event_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER REFERENCES users (user_id) ON delete CASCADE,
    timestamp       LONG,
    event_type      VARCHAR,
    operation       VARCHAR,
    entity_id       INTEGER
);






